export * from "./TestComponentsPage";
export * from "./RegisterPage";
export * from "./LoginPage";
export * from "./SettingsPage";
export * from "./ChangePasswordPage";
export * from "./MapPage";
export * from "./ResumePage";
export * from "./RankingPage";
export * from "./Challenge1Page";
